### ISSUE TITLE
Stuck - does anyone know the name of the data set that we need to open? 

### ISSUE THREAD

**Issue by BissKuttner** [DS4PS/Data-Science-Class#5]
I think that I need to open a dataset to get the answers to the questions but I can't figure out what it is. 
I am completely stuck.

**Comment by lecy** [comment]
For Lab-02 and Lab-03, you will read the tax parcels dataset from GitHub with the following commands:

```r
URL <- "https://raw.githubusercontent.com/DS4PS/Data-Science-Class/master/DATA/syr_parcels.csv"
dat <- read.csv( URL, stringsAsFactors=FALSE )
```

You can then reference the dataset by the name here, "dat", or you can select a different name when loading it.
